name: guess_pokemon

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  google_sign_in: ^6.3.0
  http: ^1.4.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  ios: true
  image_path: "assets/icons/game_logo.png"


flutter:

  uses-material-design: true
  assets:
    - assets/background_images/
    - assets/icons/

  fonts:
    - family: LuckiestGuy
      fonts:
        - asset: assets/fonts/LuckiestGuy-Regular.ttf